version: '3.7'
services:
  cphp:
    build:
      context: ./php-fpm
    volumes:
      - ./:/var/www
      - ./php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - caddy
  cmysql:
    image: mysql:5.7
    command: --sort_buffer_size=2M
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      #- /etc/localtime:/etc/localtime:ro
    networks:
      - caddy
  
  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - cmysql
    volumes:
      - ./backup:/backup
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASSWORD}
      - MAX_BACKUPS=15
      - INIT_BACKUP=1
      - CRON_TIME=0 */12 * * *
      - GZIP_LEVEL=9
      - MYSQLDUMP_OPTS=--no-tablespaces
    restart: unless-stopped
    networks:
      - caddy
  
  credis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - caddy
  caddy:
    build:
      context: ./caddy
    volumes:
      - ./:/var/www:ro
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_config:/config
      - caddy_data:/data
    depends_on:
      - cphp
    ports:
      - "80:80"
    networks:
      - caddy
    labels:
      caddy.address: "https://deada.ch"
      caddy.tls: "assada.ua@gmail.com"
      caddy.proxy.transparent: ""

  i2pd:
    image: purplei2p/i2pd:latest
    container_name: i2pd
    restart: always
    networks: [caddy]
    volumes:
      - i2pd_data:/home/i2pd/data
      - ./i2p/i2pd.conf:/home/i2pd/.i2pd/i2pd.conf:ro
      - ./i2p/tunnels.conf:/home/i2pd/.i2pd/tunnels.conf:ro
    command:
      - /usr/bin/i2pd
      - --conf=/home/i2pd/.i2pd/i2pd.conf
      - --tunconf=/home/i2pd/.i2pd/tunnels.conf
      - --log=stdout
      - --loglevel=info
      - --port=4567
      - --ntcp2.port=4567
      - --ssu2.port=4567
    ports:
      - "4567:4567/tcp"
      - "4567:4567/udp"
      - "127.0.0.1:7070:7070"

volumes:
  caddy_config:
    driver: local
  caddy_data:
    driver: local
  mysql:
    driver: local
  i2pd_data:
networks:
  caddy:
    external:
      name: assada-services
