log = stdout
loglevel = info
daemon = false

ipv4 = true
ipv6 = false
nat = false

notransit = true
share = 0
limits.transittunnels = 0

port = 4567
ntcp2.enabled = true
ntcp2.published = true
ntcp2.port = 4567
ssu2.enabled = true
ssu2.published = true
ssu2.port = 4567

http.enabled = true
http.address = 0.0.0.0
http.port = 7070
http.strictheaders = true
http.hostname = localhost
http.auth = false
socksproxy.enabled = false
socksproxy.outproxy.enabled = false
httpproxy.outproxy=